name: Release .deb

on: push

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y git-buildpackage debhelper dh-sequence-dkms

      - name: Initialize cowbuilder
        run: sudo cowbuilder --create --distribution jammy

      - name: Build igh-ethercat
        run: |
          git clone https://github.com/tutrobo/igh-ethercat.git
          cd igh-ethercat
          gbp buildpackage --git-pbuilder

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.deb'
